spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/garbage?characterEncoding=utf-8&useSSL=false&&serverTimezone=UTC
    username: root
    password: q4551060
server:
  port: 8085
file:
  upload:
    path: /User/qiu
